spring.application.name=film-forum
database.url=jdbc:mariadb://localhost:3306/film-forum
database.username=root
database.password=1234

spring.web.error.include-stacktrace=never
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
